-- MySQL Script generated by MySQL Workbench
-- Thu 20 Jan 2022 02:20:37 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema academia-atentos-db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema academia-atentos-db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `academia-atentos-db` ;
USE `academia-atentos-db` ;

-- -----------------------------------------------------
-- Table `academia-atentos-db`.`Poblaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia-atentos-db`.`Poblaciones` (
  `idPoblacion` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Provincia` VARCHAR(45) NULL,
  `CodigoPostal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPoblacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia-atentos-db`.`Personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia-atentos-db`.`Personas` (
  `idPersona` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `DNI` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) CHARACTER SET 'ascii' NULL,
  `Poblaciones_idPoblacion` INT NOT NULL,
  PRIMARY KEY (`idPersona`),
  INDEX `fk_Personas_Poblaciones1_idx` (`Poblaciones_idPoblacion` ASC) VISIBLE,
  CONSTRAINT `fk_Personas_Poblaciones1`
    FOREIGN KEY (`Poblaciones_idPoblacion`)
    REFERENCES `academia-atentos-db`.`Poblaciones` (`idPoblacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia-atentos-db`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia-atentos-db`.`Empleados` (
  `idEmpleado` INT NOT NULL,
  `Puesto` ENUM('Profesor', 'Auxiliar', 'Coodinador', 'Administrativo') NOT NULL,
  `Titulacion` VARCHAR(45) NULL,
  `Fecha_alta` DATE NULL,
  `Fecha_baja` DATE NULL,
  `Personas_idPersona` INT NOT NULL,
  `Empleados_idCoordinador` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  INDEX `fk_Empleados_Personas1_idx` (`Personas_idPersona` ASC) VISIBLE,
  INDEX `fk_Empleados_Empleados1_idx` (`Empleados_idCoordinador` ASC) VISIBLE,
  CONSTRAINT `fk_Empleados_Personas1`
    FOREIGN KEY (`Personas_idPersona`)
    REFERENCES `academia-atentos-db`.`Personas` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleados_Empleados1`
    FOREIGN KEY (`Empleados_idCoordinador`)
    REFERENCES `academia-atentos-db`.`Empleados` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia-atentos-db`.`Tutores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia-atentos-db`.`Tutores` (
  `idTutor` INT NOT NULL,
  `Tipo` ENUM('Madre', 'Padre', 'Otro') NULL,
  `Preferencia_contacto` VARCHAR(45) NULL,
  `Personas_idPersona` INT NOT NULL,
  PRIMARY KEY (`idTutor`),
  INDEX `fk_Tutores_Personas1_idx` (`Personas_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Tutores_Personas1`
    FOREIGN KEY (`Personas_idPersona`)
    REFERENCES `academia-atentos-db`.`Personas` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia-atentos-db`.`Alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia-atentos-db`.`Alumnos` (
  `idAlumno` INT NOT NULL,
  `Curso` VARCHAR(45) NOT NULL,
  `Colegio` VARCHAR(45) NULL,
  `Trastorno` TINYINT NOT NULL,
  `Repetidor` TINYINT NULL,
  `Suspensos` INT NULL,
  `Personas_idPersona` INT NOT NULL,
  `Tutores_idTutor` INT NOT NULL,
  PRIMARY KEY (`idAlumno`),
  INDEX `fk_Alumnos_Personas1_idx` (`Personas_idPersona` ASC) VISIBLE,
  INDEX `fk_Alumnos_Tutores1_idx` (`Tutores_idTutor` ASC) VISIBLE,
  CONSTRAINT `fk_Alumnos_Personas1`
    FOREIGN KEY (`Personas_idPersona`)
    REFERENCES `academia-atentos-db`.`Personas` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumnos_Tutores1`
    FOREIGN KEY (`Tutores_idTutor`)
    REFERENCES `academia-atentos-db`.`Tutores` (`idTutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia-atentos-db`.`Recibos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia-atentos-db`.`Recibos` (
  `idRecibo` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Cantidad` DECIMAL(2) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Modo` ENUM('Efectivo', 'Tarjeta', 'Bizum', 'Transferencia') NULL,
  `Alumnos_idAlumno` INT NOT NULL,
  PRIMARY KEY (`idRecibo`),
  INDEX `fk_Recibos_Alumnos1_idx` (`Alumnos_idAlumno` ASC) VISIBLE,
  CONSTRAINT `fk_Recibos_Alumnos1`
    FOREIGN KEY (`Alumnos_idAlumno`)
    REFERENCES `academia-atentos-db`.`Alumnos` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia-atentos-db`.`Aulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia-atentos-db`.`Aulas` (
  `idAula` INT NOT NULL,
  `Capacidad` INT NULL,
  `Medios` VARCHAR(45) NULL,
  PRIMARY KEY (`idAula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia-atentos-db`.`Modalidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia-atentos-db`.`Modalidades` (
  `idModalidad` INT NOT NULL,
  `Tipo_modalidad` VARCHAR(80) NULL,
  `Tipo_asistencia` ENUM('Onlines', 'Presencial', 'Mixto') NULL,
  `Tarifa` DOUBLE NULL,
  PRIMARY KEY (`idModalidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia-atentos-db`.`Matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia-atentos-db`.`Matricula` (
  `Fecha_matricula` DATE NULL,
  `Fecha_inicio` DATE NULL,
  `Alumnos_idAlumno` INT NOT NULL,
  `Modalidades_idModalidad` INT NOT NULL,
  INDEX `fk_Matricula_Alumnos1_idx` (`Alumnos_idAlumno` ASC) VISIBLE,
  INDEX `fk_Matricula_Modalidades1_idx` (`Modalidades_idModalidad` ASC) VISIBLE,
  CONSTRAINT `fk_Matricula_Alumnos1`
    FOREIGN KEY (`Alumnos_idAlumno`)
    REFERENCES `academia-atentos-db`.`Alumnos` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Modalidades1`
    FOREIGN KEY (`Modalidades_idModalidad`)
    REFERENCES `academia-atentos-db`.`Modalidades` (`idModalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia-atentos-db`.`Horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia-atentos-db`.`Horarios` (
  `Dia` VARCHAR(45) NULL,
  `Hora` VARCHAR(45) NULL,
  `Alumnos_idAlumno` INT NOT NULL,
  `Empleados_idEmpleado` INT NOT NULL,
  `Aulas_idAula` INT NOT NULL,
  INDEX `fk_Horarios_Alumnos1_idx` (`Alumnos_idAlumno` ASC) VISIBLE,
  INDEX `fk_Horarios_Empleados1_idx` (`Empleados_idEmpleado` ASC) VISIBLE,
  INDEX `fk_Horarios_Aulas1_idx` (`Aulas_idAula` ASC) VISIBLE,
  CONSTRAINT `fk_Horarios_Alumnos1`
    FOREIGN KEY (`Alumnos_idAlumno`)
    REFERENCES `academia-atentos-db`.`Alumnos` (`idAlumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horarios_Empleados1`
    FOREIGN KEY (`Empleados_idEmpleado`)
    REFERENCES `academia-atentos-db`.`Empleados` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horarios_Aulas1`
    FOREIGN KEY (`Aulas_idAula`)
    REFERENCES `academia-atentos-db`.`Aulas` (`idAula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
